In [ ]:
%load_ext autoreload
%autoreload 2
import os
import sys

parent_dir = os.path.abspath("..")
sys.path.append(parent_dir)


from functools import partial

import jax
import jax.numpy as jnp
from diffrax import (
    ODETerm,
    RecursiveCheckpointAdjoint,
    SaveAt,
    diffeqsolve,
)
from tools.integrate import integrate, scan_integrate
from tools.semi_implicite_euler import SemiImplicitEuler


def check_tree(x, y):
    return jax.tree.all(jax.tree.map(lambda x, y: jnp.allclose(x, y), x, y))


def f(t, x, z):
    return x + z[0] * z[1]


def g(t, y, z):
    return y + z[0] * z[1]


def fg(t, x_y, z):
    x, y = x_y
    out = f(t, x, z), g(t, y, z)
    return jnp.stack(out, axis=0)


def save_ys(t, y, z):
    y_red = jax.tree.reduce(lambda x, y: x + y, y)
    z_red = jax.tree.reduce(lambda x, y: x + y, z)
    return jnp.sum(y_red * t * z_red)


def reverse_integrate(ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1):
    saveat = SaveAt(ts=ts, t0=save_t0, t1=save_t1)
    return integrate(ode_terms, solver, t0, t1, dt0, y0, args, saveat)


def diffrax_integrate(
    ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1, checkpoints=10
):
    saveat = SaveAt(ts=ts, t0=save_t0, t1=save_t1)
    sol = diffeqsolve(
        ode_terms,
        solver,
        t0,
        t1,
        dt0,
        y0,
        args,
        saveat=saveat,
        adjoint=RecursiveCheckpointAdjoint(checkpoints=checkpoints),
    )
    return sol.ys


def jax_integarete(ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1):
    saveat = SaveAt(ts=ts, t0=save_t0, t1=save_t1)
    return scan_integrate(ode_terms, solver, t0, t1, dt0, y0, args, saveat=saveat)

In [19]:
from itertools import product

y0 = (jnp.array([1.0, 2.0]), jnp.array([3.0, 4.0]))
args = (2.0, 5.0)

t0 = 0.0
t1 = 10.0
dt0 = 2.0
ode_terms = (ODETerm(g), ODETerm(f))
solver = SemiImplicitEuler()
save_t0 = False
save_t1 = False
ts = jnp.array([0.0, 10.0])


diffrax_fwd = jax.jacrev(diffrax_integrate, argnums=(7), allow_int=True)(
    ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1
)
my_fwd = jax.jacrev(reverse_integrate, argnums=(7), allow_int=True)(
    ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1
)
jax_fwd = jax.jacfwd(jax_integarete, argnums=(7))(
    ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1
)

y_ct is (Array([0., 0.], dtype=float32), Array([0., 0.], dtype=float32))
y_ct is (Array([0., 0.], dtype=float32), Array([0., 0.], dtype=float32))
y_ct is (Array([1., 0.], dtype=float32), Array([0., 0.], dtype=float32))
y_ct is (Array([0., 1.], dtype=float32), Array([0., 0.], dtype=float32))
y_ct is (Array([0., 0.], dtype=float32), Array([0., 0.], dtype=float32))
y_ct is (Array([0., 0.], dtype=float32), Array([0., 0.], dtype=float32))
y_ct is (Array([0., 0.], dtype=float32), Array([1., 0.], dtype=float32))
y_ct is (Array([0., 0.], dtype=float32), Array([0., 1.], dtype=float32))
t0 is 8.0 and t1 is 10.0
final 0.0 f_adj_ts 0.0  y_ct is (Array([0., 0.], dtype=float32), Array([0., 0.], dtype=float32)) snap_adj_ts 0.0 step_adj_ts 0.0 adj_ts 0.0
final 0.0 f_adj_ts 0.0  y_ct is (Array([0., 0.], dtype=float32), Array([0., 0.], dtype=float32)) snap_adj_ts 0.0 step_adj_ts 0.0 adj_ts 0.0
final 17293.0 f_adj_ts 17293.0  y_ct is (Array([1., 0.], dtype=float32), Array([0., 0.], dtype=float32)) snap_a

In [20]:
jax_fwd

(Array([[[     0.,      0.],
         [     0.,      0.]],
 
        [[-17293.,  17293.],
         [-18686.,  18686.]]], dtype=float32),
 Array([[[     0.,      0.],
         [     0.,      0.]],
 
        [[-76335.,  76335.],
         [-82484.,  82484.]]], dtype=float32))

In [21]:
my_fwd

(Array([[[1.3000e+01, 0.0000e+00],
         [1.4000e+01, 0.0000e+00]],
 
        [[2.1670e+04, 1.7293e+04],
         [2.3640e+04, 1.8686e+04]]], dtype=float32),
 Array([[[1.1000e+01, 0.0000e+00],
         [1.2000e+01, 0.0000e+00]],
 
        [[1.7730e+04, 7.6335e+04],
         [1.9700e+04, 8.2484e+04]]], dtype=float32))

In [22]:
jax.tree.map(lambda x, y: x == y, my_fwd, jax_fwd)

(Array([[[False,  True],
         [False,  True]],
 
        [[False,  True],
         [False,  True]]], dtype=bool),
 Array([[[False,  True],
         [False,  True]],
 
        [[False,  True],
         [False,  True]]], dtype=bool))

In [6]:
check_tree(jax_fwd, my_fwd)

False

In [10]:
diffrax_fwd

(Array([[1.1000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.5100e+02, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.6290e+03, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5323e+04]], dtype=float32),
 Array([[3.3000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0890e+03, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.3470e+03, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 3.6993e+04]], dtype=float32))

In [35]:
check_tree(diffrax_fwd, my_fwd)

True

In [22]:
diffrax_fwd = diffrax_integrate(ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1)
my_fwd = reverse_integrate(ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1)
jax_fwd = jax_integarete(ode_terms, solver, t0, t1, dt0, y0, args, ts, save_t0, save_t1)

In [23]:
diffrax_fwd

(Array([  177., 36983.], dtype=float32),
 Array([  441., 89299.], dtype=float32))

In [24]:
my_fwd

(Array([  177., 36983.], dtype=float32),
 Array([  441., 89299.], dtype=float32))

In [25]:
jax_fwd

(Array([  177., 36983.], dtype=float32),
 Array([  441., 89299.], dtype=float32))

In [ ]:
y0 = (1.0, 1.0)
args = (2.0, 5)

t0 = 0.0
t1 = 10.0
dt0 = 1
ode_terms = (ODETerm(g), ODETerm(f))
solver = SemiImplicitEuler()

for save_t0, save_t1 in product([True, False], repeat=2):
    # Starting and ending t0 and t1
    saveat_t0_t1 = SaveAt(ts=jnp.arange(t0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting t0 and ending before t1
    saveat_t0_tx = SaveAt(ts=jnp.arange(t0, t1, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending at t1
    saveat_tx_t1 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending before t1
    saveat_tx_tx = SaveAt(ts=jnp.arange(t0 + dt0, t1 - dt0, dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 before t1
    saveat_t0_tx_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Gettings steps starting after t0 and jumping steps by 2 * dt0 before t1
    saveat_tx_tx_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 at t1
    saveat_t0_t1_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting after t0 and jumping steps by 2 * dt0 at t1
    saveat_tx_t1_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)

    for saveat in [
        saveat_t0_t1,
        saveat_t0_tx,
        saveat_tx_t1,
        saveat_tx_tx,
        saveat_t0_tx_2,
        saveat_tx_tx_2,
        saveat_t0_t1_2,
        saveat_tx_t1_2,
    ]:
        jax_fwd = scan_integrate(ode_terms, solver, t0, t1, dt0, y0, args, saveat)
        diffrax_fwd = diffrax_integrate(ode_terms, solver, t0, t1, dt0, y0, args, saveat)
        my_fwd = integrate(ode_terms, solver, t0, t1, dt0, y0, args, saveat)

        assert check_tree(jax_fwd, diffrax_fwd)
        assert check_tree(jax_fwd, my_fwd)
        print(f"ok for saveat {saveat.subs.ts} with t0={saveat.subs.t0} and t1={saveat.subs.t1}")

    print("=====================================")

In [ ]:
for save_t0, save_t1 in product([True, False], repeat=2):
    # Starting and ending t0 and t1
    saveat_t0_t1 = SaveAt(ts=jnp.arange(t0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting t0 and ending before t1
    saveat_t0_tx = SaveAt(ts=jnp.arange(t0, t1, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending at t1
    saveat_tx_t1 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending before t1
    saveat_tx_tx = SaveAt(ts=jnp.arange(t0 + dt0, t1 - dt0, dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 before t1
    saveat_t0_tx_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Gettings steps starting after t0 and jumping steps by 2 * dt0 before t1
    saveat_tx_tx_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 at t1
    saveat_t0_t1_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting after t0 and jumping steps by 2 * dt0 at t1
    saveat_tx_t1_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)

    for saveat in [
        saveat_t0_t1,
        saveat_t0_tx,
        saveat_tx_t1,
        saveat_tx_tx,
        saveat_t0_tx_2,
        saveat_tx_tx_2,
        saveat_t0_t1_2,
        saveat_tx_t1_2,
    ]:
        jax_bwd = jax.jacrev(scan_integrate, argnums=(5, 6), allow_int=True)(
            ode_terms, solver, t0, t1, dt0, y0, args, saveat
        )
        diffrax_bwd = jax.jacrev(diffrax_integrate, argnums=(5, 6), allow_int=True)(
            ode_terms, solver, t0, t1, dt0, y0, args, saveat
        )
        my_bwd = jax.jacrev(integrate, argnums=(5, 6), allow_int=True)(
            ode_terms, solver, t0, t1, dt0, y0, args, saveat
        )

        assert check_tree(jax_bwd, diffrax_bwd)
        assert check_tree(jax_bwd, my_bwd)
        print(f"ok for saveat {saveat.subs.ts} with t0={saveat.subs.t0} and t1={saveat.subs.t1}")

    print("=====================================")

In [ ]:
y0 = (1.0, 1.0)
args = (2.0, 5)

t0 = 0.0
t1 = 10.0
dt0 = 1

for save_t0, save_t1 in product([True, False], repeat=2):
    # Starting and ending t0 and t1
    saveat_t0_t1 = SaveAt(ts=jnp.arange(t0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting t0 and ending before t1
    saveat_t0_tx = SaveAt(ts=jnp.arange(t0, t1, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending at t1
    saveat_tx_t1 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending before t1
    saveat_tx_tx = SaveAt(ts=jnp.arange(t0 + dt0, t1 - dt0, dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 before t1
    saveat_t0_tx_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Gettings steps starting after t0 and jumping steps by 2 * dt0 before t1
    saveat_tx_tx_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 at t1
    saveat_t0_t1_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting after t0 and jumping steps by 2 * dt0 at t1
    saveat_tx_t1_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)

    for saveat in [
        saveat_t0_t1,
        saveat_t0_tx,
        saveat_tx_t1,
        saveat_tx_tx,
        saveat_t0_tx_2,
        saveat_tx_tx_2,
        saveat_t0_t1_2,
        saveat_tx_t1_2,
    ]:

        def fn(t, y, args):
            y = jax.tree.map(lambda x: 2 * x + t * args[0], y)
            return y[0] + y[1]

        diffrax_fwd = diffrax_integrate(ode_terms, solver, t0, t1, dt0, y0, args, saveat)
        my_fwd = integrate(ode_terms, solver, t0, t1, dt0, y0, args, saveat)

        assert check_tree(my_fwd, diffrax_fwd)
        print(f"ok for saveat {saveat.subs.ts} with t0={saveat.subs.t0} and t1={saveat.subs.t1}")

In [ ]:
y0 = (1.0, 1.0)
args = (2.0, 5)

t0 = 0.0
t1 = 10.0
dt0 = 1


for save_t0, save_t1 in product([True, False], repeat=2):
    # Starting and ending t0 and t1
    saveat_t0_t1 = SaveAt(ts=jnp.arange(t0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting t0 and ending before t1
    saveat_t0_tx = SaveAt(ts=jnp.arange(t0, t1, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending at t1
    saveat_tx_t1 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, dt0), t0=save_t0, t1=save_t1)
    # Starting after t0 and ending before t1
    saveat_tx_tx = SaveAt(ts=jnp.arange(t0 + dt0, t1 - dt0, dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 before t1
    saveat_t0_tx_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Gettings steps starting after t0 and jumping steps by 2 * dt0 before t1
    saveat_tx_tx_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting from t0 and jumping steps by 2 * dt0 at t1
    saveat_t0_t1_2 = SaveAt(ts=jnp.arange(t0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)
    # Getting steps starting after t0 and jumping steps by 2 * dt0 at t1
    saveat_tx_t1_2 = SaveAt(ts=jnp.arange(t0 + dt0, t1 + dt0, 2 * dt0), t0=save_t0, t1=save_t1)

    for saveat in [
        saveat_t0_t1,
        saveat_t0_tx,
        saveat_tx_t1,
        saveat_tx_tx,
        saveat_t0_tx_2,
        saveat_tx_tx_2,
        saveat_t0_t1_2,
        saveat_tx_t1_2,
    ]:

        def fn(t, y, args):
            y = jax.tree.map(lambda x: 2 * x + t * args[0], y)
            return y[0] + y[1]

        diffrax_bwd = jax.jacrev(diffrax_integrate, argnums=(5, 6), allow_int=True)(
            ode_terms, solver, t0, t1, dt0, y0, args, saveat
        )
        my_bwd = jax.jacrev(integrate, argnums=(5, 6), allow_int=True)(
            ode_terms, solver, t0, t1, dt0, y0, args, saveat
        )

        assert check_tree(my_bwd, diffrax_bwd)
        print(f"ok for saveat {saveat.subs.ts} with t0={saveat.subs.t0} and t1={saveat.subs.t1}")

In [ ]:
def fn(t, y, args):
    z, g = args
    y = jax.tree.map(lambda x: 2 * x + t * z**4, y)

    return y[0] + y[1]


saveat = SaveAt(ts=[3, 8], t1=save_t1, fn=fn)

t0 = 0.0
t1 = 10.0
dt0 = 0.5


@jax.jit
@partial(jax.jacrev, argnums=(0, 1), allow_int=True)
def wrapped_integrate(y0, args):
    return integrate(y0, args, ode_terms, solver, t0, t1, dt0, saveat)


@jax.jit
@partial(jax.jacrev, argnums=(0, 1), allow_int=True)
def wrapped_jax_integrate(y0, args):
    return scan_integrate(y0, args, ode_terms, solver, t0, t1, dt0, saveat)


@jax.jit
@partial(jax.jacrev, argnums=(0, 1), allow_int=True)
def wrapped_diffrax_integrate(y0, args):
    return diffrax_integrate(ode_terms, solver, y0, args, t0, t1, dt0, saveat, checkpoints=10)

In [ ]:
%timeit jax.tree.map(lambda x : x.block_until_ready() , wrapped_jax_integrate(y0 , args))
%timeit jax.tree.map(lambda x : x.block_until_ready() , wrapped_integrate(y0 , args))
%timeit jax.tree.map(lambda x : x.block_until_ready() ,wrapped_diffrax_integrate(y0 , args))

In [ ]:
jax_mem = wrapped_jax_integrate.lower(y0, args).compile().memory_analysis().temp_size_in_bytes
my_mem = wrapped_integrate.lower(y0, args).compile().memory_analysis().temp_size_in_bytes
diffrax_mem = (
    wrapped_diffrax_integrate.lower(y0, args).compile().memory_analysis().temp_size_in_bytes
)

print(f"Jax memory is {jax_mem} , My memory is {my_mem} , Diffrax memory is {diffrax_mem}")